name: CI Phase - Build and Push Spring Boot Image

on: workflow_call

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/moduleregister

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Build app
        run: ./gradlew build -DskipTests=true

      - name: Generate image tag
        id: vars
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "tag=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: |
          docker build \
            -t $IMAGE_NAME:${{ steps.vars.outputs.tag }} \
            -t $IMAGE_NAME:latest .
          echo "Docker image built successfully."

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image to DockerHub
        run: |
          docker push $IMAGE_NAME:${{ steps.vars.outputs.tag }}
          docker push $IMAGE_NAME:latest
